config/routes.rb
GoogleAuthExample::Application.routes.draw do
  devise_for :users, :controllers => {  :registrations => 'users/registrations' }

  #get "assignments/new", via: 'get'
  #get 'auth/:provider/callback', to: 'sessions#create'
  #get 'auth/failure', to: redirect('/')
  #get 'signout', to: 'sessions#destroy', as: 'signout'
  #get 'post-help', to:'assignments#new'
  get 'profile', to: 'users#show'
 # get 'edit', to: 'sessions#edit'
  get 'edit/:id', to: 'assignments#edit'
   get '/inbox', to: 'messages#index'
  get '/:name', to: 'subsubjects#show'


 


  #resource :sessions, only: [:show, :edit, :delete, :create]
  resource :user, only: [:edit, :show]
  resource :home, only: [:show]
  resources :assignments, only:[:show, :edit, :update, :create, :new, :destroy]
  resources :subjects, only: [:show]
  resources :subsubjects, only: [:show]
  resource :responses, only: [:create, :destroy]
  resources :messages, only: [:index, :show, :create, :destroy, :new]

  root to: "home#show"
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
belongs_to :user
validates :description,  presence: true, length: { minimum: 30 }
validates :points, presence:true, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 10, }
validates :subsubject, presence:true, numericality: {greater_than: 0 ,:message => "choose and option without a -- in front" }



end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

 def show
 	logged_in_user
  @assignment = Assignment.find(params[:id])
 	@user = User.find(@assignment.UID)
  @answer = Response.new
  @answers = Response.where(assignmentID: @assignment.id)
  @done = Response.find_by(assignmentID: @assignment, UID: current_user.id)
  @message = Message.new
 	#byebug
  rescue ActiveRecord::RecordNotFound
  redirect_to root_url, :flash => { :error => "Record not found." }

 end

 def new
 	logged_in_user
 	@assignment = Assignment.new
 	@subs = Subject.all.map { |s| (["--"+s.name, 0]) }
 	index = 1
 	@subs.length.times do |x|
		 Subsubject.where(subjectID: x+1).each do |i|
			@subs.insert(index, [i.name, i.id])
			index+= 1
		end
		index+= 1
	end

 end
 
  def create
  	logged_in_user
  	@assignment = Assignment.new(params[:assignment].permit!)

  	if  @assignment.save && (@assignment.points <= current_user.points)  
  		@assignment.UID = current_user.id
  		@assignment.completed = false
  		@assignment.save!
  		minusPoints
  		flash[:success] = "post successfully uploaded"
  		redirect_to @assignment
  	else
  		if @assignment.points && @assignment.points > current_user.points
  			flash[:danger] = "cannot use more points than you have"
  		end
  		render 'new'
  	end
  	
  end
  
  def edit
  	logged_in_user
  	@assignment = Assignment.find(params[:id])
  	check_user(@assignment)
  end

  def update
  	logged_in_user
  	@assignment = Assignment.find(params[:id])
  	check_user(@assignment)
   	x = @assignment.points
   	y = current_user.points + x

  	if (@assignment.points <= x) && @assignment.update_attributes(params[:assignment].permit!) 
  		current_user.update(points: x)
  		@assignment.save!
  		minusPoints
  		flash[:success] = "post successfully updated"
  		redirect_to @assignment
  	else
  		if @assignment.points > current_user.points
  			flash[:danger] = "cannot use more points than you have"
  		end
  		render 'edit'
  	end
  end

  def choose
    byebug
  end

  def destroy
    @assignment  = Assignment.find(params[:id])
    u =  User.find(session[:user_id])
    p = @assignment.points +  u.points
    u.update(points: p)
    answers = Response.where(assignmentID: @assignment.id)
    answers.each do |x|
      Message.create(sender: current_user.id, recever: x.UID, subject: "Deleted asignment", message: "A question you responded to was deleted before a winner was chosen. We have given you half of the points the question was worth because of this inconvenice to you.", opened: false)
      sorryPonits = User.find(x.UID).points + (@assignment.points/2)
      User.find(x.UID).update(points: sorryPonits)
      x.delete
    end
    @assignment.delete
    redirect_to root_path
  end


include SessionsHelper
  private

    # Confirms a logged-in user.
    def logged_in_user
      unless current_user        
        redirect_to root_path
      end
  end
  private
  
  def minusPoints
  	x = current_user.id
  	q = current_user.points - @assignment.points
  	User.find(x).update(points: q)
  end

  def check_user(assignment)
  	unless current_user == User.find(assignment.UID)
  		redirect_to assignment
  	end	
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
	def direct(x)
		redirect_to edit_location_path(x)
	end

end

app/views/assignments/edit.html.erb
<% @assignment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
<%= form_for(@assignment) do |f| %>
		
	  <div id="assignment-description">
      	<%= f.label :description %><br>
      	<%= f.text_area :description%>
  	  </div>
  	  <div id="points">
      You have <%=current_user.points + @assignment.points %> points to use <br>
      <%= f.text_field :points%>
  	  </div>	
  	  <div id="subject">
  
 <%=f.label :subject%><br>
 <%= f.select :subsubject, options_for_select(subs), class:  'form-control' %><br>
</div>

      <%= f.submit "Create Post", class: "btn btn-primary" %>
 <% end %>

app/views/assignments/new.html.erb
<% @assignment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
<%= form_for(@assignment) do |f| %>
		
	
      	<%= f.label :description %><br>
      	<%= f.text_area :description, placeholder: "descirbe your assignemnt here", class:  'form-control'%>
  	<%= f.label :duedate %><br>
     <%= f.text_field :duedate, placeholder: "month/day/year", class:  'form-control'%><br>
      You have <%=current_user.points %> 
      <%= f.label :points %> <br>
      <%= f.text_field :points, placeholder: "number of points", class:  'form-control'%>
  	   <%=f.label :subject%><br>
 <%= f.select :subsubject, options_for_select(subs), class:  'form-control' %><br>


      <%= f.submit "Create Post", class: "btn btn-primary" %>
 <% end %>

app/views/assignments/show.html.erb
<%if current_user.id == @assignment.UID %>
	<%= link_to "Delete post",  @assigment,  method: :delete %> <br>
<%end%>

Posted by <%= @user.userName %>
<br>
Due on <%= @assignment.duedate %> worth <%= @assignment.points%> points 

<%= link_to Subsubject.find(@assignment.subsubject).name, Subsubject.find(@assignment.subsubject)%>


<%=@assignment.description %> 
<% if @assignment.UID == current_user.id %>  
	<%= link_to "edit", edit_assignment_path(@assignment) %>
<%end %>

<%if @assignment.UID != current_user.id && !@done %>
 <br>
 <%= link_to_function "Let them know you're working on it", 'showMessage()'%>
 	<div id='message' class = 'hide'>
 		<%= form_for(@message) do |f| %>
 			<%= f.text_field :subject, placeholder: "subject", class:  'form-control'  %>
 			<%= f.text_area :message, placeholder: "message", class:  'form-control' %>
 			<%= f.hidden_field :recever, value: @user.id %>
 			<%= f.submit "Send Message", class: "btn btn-primary" %>
 		<%end%>
 	</div>
  <%= form_for (@answer) do |f|%>
  	<%=f.text_area :response, placeholder: "type your answer here",class:  'form-control' %>
 	<%= f.hidden_field :assignmentID, value: @assignment.id %>
  	<%= f.submit "Send Answer", class: "btn btn-primary" %>
  <%end%>
<%elsif @done %>
	<br>
	Your answer: <%= @done.response %>
<%elsif current_user.id ==  @assignment.UID%>
	<%= form_for @assignment do |f|%>
		<% @answers.each do |ans|%>
		 <div>
		 <%= f.radio_button :doneBy, ans.UID%>
		 <%= f.label :doneBy, ans.response %>
   		</div>
   		 <%end%>
   		 <%= f.submit "Choose solution", class: "btn btn-primary" %>
	<%end%>
	
<%end%>